### ISSUE TITLE
jekyll serve error

### ISSUE THREAD

**Issue by mort3za** [biomadeira/jasper#29]
Hi, Thanks for building such a nice template.
I have an issue running jekyll locally.
After clone, configure _config.yml and `bundle install`, just ran `jekyll serve` and got this error.

```
/usr/lib/ruby/vendor_ruby/liquid/htmltags.rb:43: warning: key "index0" is duplicated and overwritten on line 46
Configuration from /home/morteza/www/nik/nikmodern.github.io/_config.yml
Building site: /home/morteza/www/nik/nikmodern.github.io -> serve
/home/morteza/www/nik/nikmodern.github.io/_plugins/jekyll-catgenerator.rb:26:in `paginate': uninitialized constant Jekyll::Paginate (NameError)
    from /home/morteza/www/nik/nikmodern.github.io/_plugins/jekyll-catgenerator.rb:16:in `build_subpages'
    from /home/morteza/www/nik/nikmodern.github.io/_plugins/jekyll-catgenerator.rb:9:in `block in generate'
    from /home/morteza/www/nik/nikmodern.github.io/_plugins/jekyll-catgenerator.rb:8:in `each'
    from /home/morteza/www/nik/nikmodern.github.io/_plugins/jekyll-catgenerator.rb:8:in `generate'
    from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:184:in `block in generate'
    from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:183:in `each'
    from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:183:in `generate'
    from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:39:in `process'
    from /usr/bin/jekyll:250:in `<main>'

```

**Comment by mort3za** [comment]
Before this error i had some other errors about jekyll plugins (?) which by running sudo gem install _that_plugin_ solved.

**Comment by mort3za** [comment]
Solved by this:
`sudo gem install github-pages`
