### ISSUE TITLE
jekyll serve error

### ISSUE THREAD

**Issue by zrss** [biomadeira/jasper#5]
when I run jekyll serve in jasper directory just give me these info    

```
/usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- jekyll-paginate (LoadError)
    from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:27:in `each'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:27:in `require_gems'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/jekyll-3.0.0/lib/jekyll/site.rb:97:in `setup'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/jekyll-3.0.0/lib/jekyll/site.rb:49:in `initialize'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `new'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `process'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/jekyll-3.0.0/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.1.1/bin/jekyll:23:in `load'
    from /usr/local/rvm/gems/ruby-2.1.1/bin/jekyll:23:in `<main>'
    from /usr/local/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
    from /usr/local/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by zrss** [comment]
lack off some necessary dependencies as **jekyll-paginate**
